platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.xcar.com.cn/iOS/XCRSpecs.git'

target 'XCRScrollPageView' do
 pod 'XCRTitleScrollView'
 pod 'MJRefresh', '3.1.15'
end
